sudo: required
services:
- docker
language: c

env:
  matrix:
  - JOB_ARCH=amd64 JOB_NATIVE_BUILD=1
  - JOB_ARCH=arm64
  - JOB_ARCH=armel
  - JOB_ARCH=armhf
  - JOB_ARCH=i386 JOB_NATIVE_BUILD=1
  - JOB_ARCH=mips
  - JOB_ARCH=mips64el
  - JOB_ARCH=mipsel
  - JOB_ARCH=ppc64el
  - JOB_ARCH=s390x
  global:
  - DOCKER_EXEC="docker exec test_container"
  - BINTRAY_USER=laarid
  - BINTRAY_REPO=debian
  - BINTRAY_DESC="Android dummy library"
  - BINTRAY_COMPONENT=main
  - BINTRAY_SUITE=sid

addons:
  apt:
    packages:
    - dpkg-dev

before_install:
- if [ -z "${JOB_NATIVE_BUILD}" ]; then
    docker run --rm --privileged vicamo/binfmt-qemu:bionic;
    cat /proc/sys/fs/binfmt_misc/qemu-*;
  fi
- |
  docker run --detach --tty \
    --name test_container \
    --volume ${TRAVIS_BUILD_DIR%${TRAVIS_REPO_SLUG}}:${TRAVIS_BUILD_DIR%${TRAVIS_REPO_SLUG}} \
    --workdir ${TRAVIS_BUILD_DIR} \
    vicamo/debian:${BINTRAY_SUITE}-$(if [ -n "${JOB_NATIVE_BUILD}" ]; then echo ${JOB_ARCH}; else dpkg --print-architecture; fi) \
    /bin/bash

install:
- if [ -z "${JOB_NATIVE_BUILD}" ]; then
    ${DOCKER_EXEC} dpkg --add-architecture ${JOB_ARCH};
  fi
- ${DOCKER_EXEC} apt-get update --quiet --quiet
- ${DOCKER_EXEC} apt-get install --no-install-recommends --yes
    devscripts
    equivs
- |
  ${DOCKER_EXEC} mk-build-deps \
    --host-arch ${JOB_ARCH} \
    --install --remove \
    --tool 'apt-get -o Debug::pkgProblemResolver=yes --no-install-recommends -y'

script:
- ${DOCKER_EXEC} dpkg-buildpackage --host-arch ${JOB_ARCH} -i -us -uc -b
- ${DOCKER_EXEC} make -C build distcheck
- git status | grep 'working tree clean'

before_deploy:
- |
  cat .bintray.json.in | \
    sed -e "s#@BINTRAY_PACKAGE@#$(${DOCKER_EXEC} dpkg-parsechangelog | grep ^Source: | awk '{print $2}')#g" \
        -e "s#@BINTRAY_USER@#${BINTRAY_USER}#g" \
        -e "s#@BINTRAY_REPO@#${BINTRAY_REPO}#g" \
        -e "s#@BINTRAY_DESC@#${BINTRAY_DESC}#g" \
        -e "s#@GITHUB_REPO@#${TRAVIS_REPO_SLUG}#g" \
        -e "s#@BINTRAY_VERSION@#$(${DOCKER_EXEC} dpkg-parsechangelog | grep ^Version: | awk '{print $2}')#g" \
        -e "s#@BINTRAY_RELEASE_DATE@#$(date -Iseconds --date="$(${DOCKER_EXEC} dpkg-parsechangelog | grep ^Date: | cut -d ' ' -f 2-)")#g" \
        -e "s#@BINTRAY_OUTDIR@#$(dirname ${TRAVIS_BUILD_DIR})#g" \
        -e "s#@BINTRAY_POOLABBR@#$(${DOCKER_EXEC} dpkg-parsechangelog | grep ^Source: | awk '{print $2}' | cut -c1)#g" \
        -e "s#@BINTRAY_SUITE@#${BINTRAY_SUITE}#g" \
        -e "s#@BINTRAY_COMPONENT@#${BINTRAY_COMPONENT}#g" \
        -e "s#@BINTRAY_ARCH@#${JOB_ARCH}#g" | \
    tee bintray.json.arched
- |
  cat .bintray.json.in | \
    sed -e "s#@BINTRAY_PACKAGE@#$(${DOCKER_EXEC} dpkg-parsechangelog | grep ^Source: | awk '{print $2}')#g" \
        -e "s#@BINTRAY_USER@#${BINTRAY_USER}#g" \
        -e "s#@BINTRAY_REPO@#${BINTRAY_REPO}#g" \
        -e "s#@BINTRAY_DESC@#${BINTRAY_DESC}#g" \
        -e "s#@GITHUB_REPO@#${TRAVIS_REPO_SLUG}#g" \
        -e "s#@BINTRAY_VERSION@#$(${DOCKER_EXEC} dpkg-parsechangelog | grep ^Version: | awk '{print $2}')#g" \
        -e "s#@BINTRAY_RELEASE_DATE@#$(date -Iseconds --date="$(${DOCKER_EXEC} dpkg-parsechangelog | grep ^Date: | cut -d ' ' -f 2-)")#g" \
        -e "s#@BINTRAY_OUTDIR@#$(dirname ${TRAVIS_BUILD_DIR})#g" \
        -e "s#@BINTRAY_POOLABBR@#$(${DOCKER_EXEC} dpkg-parsechangelog | grep ^Source: | awk '{print $2}' | cut -c1)#g" \
        -e "s#@BINTRAY_SUITE@#${BINTRAY_SUITE}#g" \
        -e "s#@BINTRAY_COMPONENT@#${BINTRAY_COMPONENT}#g" \
        -e "s#@BINTRAY_ARCH@#all#g" | \
    tee bintray.json.all

deploy:
- provider: bintray
  file: bintray.json.arched
  user: vicamo
  key:
    secure: "lInkO/7Kf9n3vVghmmqcEe/7dOIjXXZUL1xlidDqg22clSTC04rXrgkEMdcibhWIXLC0mmWvB73CwwoMOIMEwQoAi5Si0Ks093agEOgveOy3V60VLws9Apuh0ANSCRPID6coO6cK8aDdUty4XsCT3MI8WjKbugci9Ujfmkg57MH4akeYa+mBCmxnxMDwV6fJVS+1u2Fb0YgaP7ExP2VqsGSuULgmwCcSZ7B0dE1FObZiiKK+U2xqNJJVRwC45IgjYfGAJsIAtLtMJrE/yApogdX9Tu/LdXiwqopHCpB4djBBfhCqkACJYUMmWZVRTRC1Zwzxh+vVVZjNY36SbYHbaJCuat3U0puae3JwlKOWJPt2PTYlVC2p7f9TFOuwO4joQjg5rJ9olHZfbgk19r+3BThHSqvxuOIYnNxeaNT2D27pQZmA4UZmPz2QxPjUqGq1wDqo270qlrnen76v/YIsO+aHLEOOvQSor1JYG5GyoLC/3E8ip4sC5Gbq+5+Djn2mRZKgv4XXcAkqmH+bhL/+/jBqWnGtOYnf20T7DMTOrIWFCxSsUpFfBzia2TQ7BAkhfW7FNKizafo+gl15qbUmwVoywWVi6xeL6C06MRnwxWdGWaXbYnwslivLgoV8lIcloCJB7Z2b6QexuNSNUNqqOP/duJXx4Qmt8rBRUBnONnA="
  skip_cleanup: true
  on:
    branch: for-laarid/debian/sid
- provider: bintray
  file: bintray.json.all
  user: vicamo
  key:
    secure: "lInkO/7Kf9n3vVghmmqcEe/7dOIjXXZUL1xlidDqg22clSTC04rXrgkEMdcibhWIXLC0mmWvB73CwwoMOIMEwQoAi5Si0Ks093agEOgveOy3V60VLws9Apuh0ANSCRPID6coO6cK8aDdUty4XsCT3MI8WjKbugci9Ujfmkg57MH4akeYa+mBCmxnxMDwV6fJVS+1u2Fb0YgaP7ExP2VqsGSuULgmwCcSZ7B0dE1FObZiiKK+U2xqNJJVRwC45IgjYfGAJsIAtLtMJrE/yApogdX9Tu/LdXiwqopHCpB4djBBfhCqkACJYUMmWZVRTRC1Zwzxh+vVVZjNY36SbYHbaJCuat3U0puae3JwlKOWJPt2PTYlVC2p7f9TFOuwO4joQjg5rJ9olHZfbgk19r+3BThHSqvxuOIYnNxeaNT2D27pQZmA4UZmPz2QxPjUqGq1wDqo270qlrnen76v/YIsO+aHLEOOvQSor1JYG5GyoLC/3E8ip4sC5Gbq+5+Djn2mRZKgv4XXcAkqmH+bhL/+/jBqWnGtOYnf20T7DMTOrIWFCxSsUpFfBzia2TQ7BAkhfW7FNKizafo+gl15qbUmwVoywWVi6xeL6C06MRnwxWdGWaXbYnwslivLgoV8lIcloCJB7Z2b6QexuNSNUNqqOP/duJXx4Qmt8rBRUBnONnA="
  skip_cleanup: true
  on:
    branch: for-laarid/debian/sid

notifications:
  slack:
    rooms:
    - secure: "QdHUOfJCUukvRzp0XuciEX+nFktSMnepKJoKcm72+3QT3xRiUzq9ptex0BJp291YQu2C8K8bqdSJ4vPK+4YSNh4Sr7xSHk7I9yoqVkv2f2Udd+a9Im8a553PizO+cM8pVmpBM1bWq653R8xhvQX4d6uHz0SCYX2lv0qxvVPf/QxOIox+Z3J2Uu4MBLW4kLBCDjEfbRrxyaKE3Ik8ElsaRBgvhCJc5cd1G191fkkbc76XevifKi7RjSvo4tpvHHzN7WWGI8WYQDF1B4uARSd1twzWMQHdhfJkl0tIvF58mCrryzhY4zLBe4WDeccksNPAblGCRgSCgae4kvLV3l2qJuoaislKal6yQclFVF2KAfVplE+18x+KU3wopMgvEA/zDsgsSd76aPE3MIfh9hs0UxubKR4r6dy+wIQPYZxtYZF/J2Q7m6rO8deDVgIQ/bUqzZ8mS74UwaRg3CL+7XPaeeHuxGKhvfwglZmOGL0yV0040iV7Cr3/HaYIlGNr7WSK+tgvesskpj58D8MJEklqHVGsjghxB9fdIhrHjm0myytpeolx6rVfB9yn/FPm8S1RXQNyJLeOJHwKnZ7At1OFOEye3QMiba4unX6HKd8U5H99o7NMDkMSdpr7zRCne3aXi5rt/PAukRk2nn8RJmh65EuCQ8mTy+3i19zMTq1ScJg="
